gohey/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from goheys import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('goheys.urls'),name='goheys'),
    path('users/',include('users.urls'),name='users'),
    ]

goheys/urls.py
from django.urls import path,re_path
from goheys import views
app_name = 'goheys'
urlpatterns = [
    path('', views.index,name='index'),
    path('index/',views.index,name='index'),
    path('topics/',views.topics,name='topics'),
    re_path('topics/(?P<topic_id>\d+)',views.topic,name='topic'),
    path('new_topic/',views.new_topic,name='new_topic'),
    re_path('new_entry/(?P<topic_id>\d+)',views.new_entry,name='new_entry'),
    re_path('edit_entry/(?P<entry_id>\d+)',views.edit_entry,name='edit_entry'),
]

users/urls.py
from django.urls import path,re_path
from django.contrib.auth.views import login
from . import views
app_name = 'users'

urlpatterns = [
    path('login/',login,{'template_name': 'users/login.html'},name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('register/',views.register,name='register')

]

goheys/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

goheys/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'lext': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'lext': ''}
        widgets = {'text':forms.Textarea(attrs={'clos':80})}


goheys/views.py
from django.shortcuts import render
from goheys.models import Topic
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .forms import TopicForm,EntryForm
from .models import Topic,Entry
from django.contrib.auth.decorators import login_required



def index(request):
    return render(request,'goheys/index.html')

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return HttpResponseRedirect(reverse('goheys:topics'))

    context = {'form':form}
    return render(request,'goheys/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('goheys:topic',args=[topic_id]))

    context = {'topic':topic,'form':form}
    return render(request,'goheys/new_entry.html',context)

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'goheys/topics.html', context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request, 'goheys/topic.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('goheys:topic',
                                        args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'goheys/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth .forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('goheys:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('goheys:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)
# Create your views here.

goheys/templates/goheys/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>Go Hey</title>
      


    {% bootstrap_css %}
    {% bootstrap_javascript %}

 <style>
  body
   {
            background-color:#b0c4de;
   }
   </style>
  </head>


    <!-- Static navbar -->

<body class="hold-transition skin-blue-light layout-top-nav fixed">
<div class="wrapper">
  <header class="main-header">
    <!-- 导航 -->

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'goheys:index' %}">Go Hey</a>
         </div>

      </div>
	        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                
	          <ul class="nav navbar-nav">
	            	            <li class="active"><a href="{% url 'goheys:index' %}">首页<span class="sr-only">(current)</span></a></li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">前端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/html5.html">html5</a></li>
		                		                	<li><a href="http://93jc.cn/module/js.html">js</a></li>
		                		                	<li><a href="http://93jc.cn/module/jq.html">jq</a></li>
		                		                	<li><a href="http://93jc.cn/module/其他.html">其他</a></li>
		                		                	<li><a href="http://93jc.cn/module/ajax.html">ajax</a></li>
		                		                	<li><a href="http://93jc.cn/module/css.html">css</a></li>
                                                    <li><a href="#">呵呵</a></li>
		                		              </ul>                                     
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">后端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/php.html">php</a></li>
		                		                	<li><a href="http://93jc.cn/module/java.html">java</a></li>
		                		                	<li><a href="http://93jc.cn/module/数据库.html">数据库</a></li>
		                		                	<li><a href="http://93jc.cn/module/python.html">python</a></li>
		                		                	<li><a href="http://93jc.cn/module/C sharp.html">C sharp</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">移动端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/android.html">android</a></li>
		                		                	<li><a href="http://93jc.cn/module/ios.html">ios</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">服务器/os <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/apache.html">apache</a></li>
		                		                	<li><a href="http://93jc.cn/module/nginx.html">nginx</a></li>
		                		                	<li><a href="http://93jc.cn/module/windows.html">windows</a></li>
		                		                	<li><a href="http://93jc.cn/module/mac.html">mac</a></li>
		                		                	<li><a href="http://93jc.cn/module/linux.html">linux</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">生活娱乐 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/读书.html">读书</a></li>
		                		                	<li><a href="http://93jc.cn/module/音乐.html">音乐</a></li>
		                		                	<li><a href="http://93jc.cn/module/健身.html">健身</a></li>
		                		                	<li><a href="http://93jc.cn/module/游戏.html">游戏</a></li>
		                		                	<li><a href="http://93jc.cn/module/情感.html">情感</a></li>
		                		              </ul>
            <li>
       </div>
            <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
             <ul class="nav navbar-nav ">
             <li><a href="{% url 'goheys:topics' %}">Topics</a></li>
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>

           </li>     
            {% endif %}



 
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

goheys/templates/goheys/base1.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="zh-hans">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>Go Hey</title>
      


    {% bootstrap_css %}

    {% bootstrap_javascript %}

 <style>
  body
   {
            background-color:#b0c4de;
   }
   </style>
  </head>


    <!-- Static navbar -->

<body class="hold-transition skin-blue-light layout-top-nav fixed">
<div class="wrapper">
  <header class="main-header">
    <!-- 导航 -->

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'goheys:index' %}">Go Hey</a>
         </div>

      </div>
	        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                
	          <ul class="nav navbar-nav">
	            	            <li class="active"><a href="{% url 'goheys:index' %}">首页<span class="sr-only">(current)</span></a></li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">前端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/html5.html">html5</a></li>
		                		                	<li><a href="http://93jc.cn/module/js.html">js</a></li>
		                		                	<li><a href="http://93jc.cn/module/jq.html">jq</a></li>
		                		                	<li><a href="http://93jc.cn/module/其他.html">其他</a></li>
		                		                	<li><a href="http://93jc.cn/module/ajax.html">ajax</a></li>
		                		                	<li><a href="http://93jc.cn/module/css.html">css</a></li>
                                                    <li><a href="#">呵呵</a></li>
		                		              </ul>                                     
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">后端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/php.html">php</a></li>
		                		                	<li><a href="http://93jc.cn/module/java.html">java</a></li>
		                		                	<li><a href="http://93jc.cn/module/数据库.html">数据库</a></li>
		                		                	<li><a href="http://93jc.cn/module/python.html">python</a></li>
		                		                	<li><a href="http://93jc.cn/module/C sharp.html">C sharp</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">移动端 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/android.html">android</a></li>
		                		                	<li><a href="http://93jc.cn/module/ios.html">ios</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">服务器/os <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/apache.html">apache</a></li>
		                		                	<li><a href="http://93jc.cn/module/nginx.html">nginx</a></li>
		                		                	<li><a href="http://93jc.cn/module/windows.html">windows</a></li>
		                		                	<li><a href="http://93jc.cn/module/mac.html">mac</a></li>
		                		                	<li><a href="http://93jc.cn/module/linux.html">linux</a></li>
		                		              </ul>
		            </li>
	                                <li class="dropdown ">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown">生活娱乐 <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                		                	<li><a href="http://93jc.cn/module/读书.html">读书</a></li>
		                		                	<li><a href="http://93jc.cn/module/音乐.html">音乐</a></li>
		                		                	<li><a href="http://93jc.cn/module/健身.html">健身</a></li>
		                		                	<li><a href="http://93jc.cn/module/游戏.html">游戏</a></li>
		                		                	<li><a href="http://93jc.cn/module/情感.html">情感</a></li>
		                		              </ul>
            <li>
       </div>
            <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
             <ul class="nav navbar-nav ">
             <li><a href="{% url 'goheys:topics' %}">Topics</a></li>
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>

           </li>     
            {% endif %}



 
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

goheys/templates/goheys/edit_entry.html
{% extends "goheys/base.html" %}
{% block content %}

    <P><a href="{% url 'goheys:topic' topic.id %}">{{ topic }}</a> </P>

    <P>Edit entry:</P>
    <form action="{% url 'goheys:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
  </form>

{% endblock content %}
<

goheys/templates/goheys/index2.html
{% extends "goheys/base.html" %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

{% block header %}
  <div class='jumbotron'>
      <h2>学习随笔</h2>
  </div>
{% endblock %}

{% block content %}
  <h3>
    <a href="{% url 'users:register' %}">来注册一个账号吧</a> 学习和记录你学习过程中遇到的问题和积累经验.
  </h3>
  <h3>
    当你有所收获的时候，记得要随时随地记下来哦.
  </h3>

<h3>
Gohey
这是我的网站，我在慢慢完善它
</h3>
{% endblock content %}

goheys/templates/goheys/new_entry.html
{% extends "goheys/base.html" %}
{% block content %}

    <P><a href="{% url 'goheys:topic' topic.id %}">{{ topic }}</a> </P>

    <P>Add a new entry:</P>
    <form action="{% url 'goheys:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
  </form>

{% endblock content %}

goheys/templates/goheys/new_topic.html
{% extends "goheys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'goheys:new_topic' %}" method='post'
      class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}

  </form>

{% endblock content %}

goheys/templates/goheys/topic.html
{% extends 'goheys/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'goheys:new_entry' topic.id %}">add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'goheys:edit_entry' entry.id %}">
              edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
  {% empty %}
    There are no entries for this topic yet.
  {% endfor %}

{% endblock content %}

goheys/templates/goheys/topics.html
{% extends "goheys/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'goheys:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'goheys:new_topic' %}">Add new topic</h3>

{% endblock content %}

users/templates/users/login.html
{% extends "goheys/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'goheys:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "goheys/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'goheys:index' %}" />
  </form>

{% endblock content %}